{% set name = "plottoolbox" %}
{% set version = "105.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plottoolbox-{{ version }}.tar.gz
  sha256: 5be624785114948cd28b9969d76496e3ae9085820462ef146d9046852ce1b836

build:
  entry_points:
    - plottoolbox = plottoolbox.plottoolbox:_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cltoolbox >=1.0.0
    - numpy
    - scipy
    - pandas
    - pydantic
    - matplotlib-base
    - dateparser
    - pint !=0.21*
    - pint-pandas
    - tabulate
    - xlsxwriter

test:
  imports:
    - plottoolbox
  commands:
    - pip check
    - plottoolbox --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Command line script and Python library to make plots from data files.
  home: https://pypi.org/project/plottoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
