{% set name = "plottoolbox" %}
{% set version = "104.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plottoolbox-{{ version }}.tar.gz
  sha256: 19f14808d9d8d4f397194b524a46b87a42322e721ae27662c28a707b629a8727

build:
  entry_points:
    - plottoolbox = plottoolbox.plottoolbox:_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - cltoolbox >=1.0.0
    - numpy
    - scipy
    - pandas
    - pydantic
    - typing-extensions
    - toolbox_utils >=3.0.0,<4.0.0
    - matplotlib-base

test:
  imports:
    - plottoolbox
  commands:
    - pip check
    - plottoolbox --help
  requires:
    - pip

about:
  summary: Command line script and Python library to make plots from data files.
  home: https://pypi.org/project/plottoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
